AWSTemplateFormatVersion: '2010-09-09'
Description: RDS Instance with PostgreSQL

Resources:
  MyRDSInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: '20'
      DBInstanceClass: db.t2.micro
      Engine: postgres
      EngineVersion: '15.3-R2'  # Replace with the latest PostgreSQL version available
      MasterUsername: admin
      MasterUserPassword: Password123
      MultiAZ: false
      PubliclyAccessible: true

Outputs:
  RDSEndpoint:
    Description: Endpoint of the RDS instance
    Value: !GetAtt MyRDSInstance.Endpoint.Address

